name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:

  workflow_dispatch:

permissions:
  actions: read
  checks: write
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: write

jobs:

  build-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: zulu

    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      env:
        OAUTH_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
        COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}
      run: |
        rm -rf app/src/main/res/raw/example_oauth.json
        echo $(cat oauth.json.template) > app/src/main/res/raw/oauth.json
        chmod +x gradlew
        ./gradlew build -x lint

